'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Building2, CalendarDays, Instagram, MapPin, Phone, Save, Sparkles } from 'lucide-react';

type Settings={id:string;team_name:string;short_name:string;slogan:string;description:string;location:string;phone:string;instagram:string;founded_at:string;meeting_text:string;join_intro:string};
const empty:Settings={id:'main',team_name:'',short_name:'',slogan:'',description:'',location:'',phone:'',instagram:'',founded_at:'',meeting_text:'',join_intro:''};
export default function AdminSettingsPage(){
 const[data,setData]=useState<Settings>(empty);const[loading,setLoading]=useState(true);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
 async function load(){setLoading(true);setErr('');const res=await fetch('/api/admin/settings');const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok)return setErr(json.error||'تعذر تحميل الإعدادات');setData({...empty,...json.settings});if(json.warning)setErr(json.warning)}
 useEffect(()=>{load()},[]);
 async function save(e:FormEvent){e.preventDefault();setLoading(true);setErr('');setMsg('');const res=await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok)return setErr(json.error||'تعذر حفظ الإعدادات');setMsg('تم حفظ إعدادات الموقع بنجاح. ستظهر التغييرات في الواجهة العامة.');setData(json.settings||data)}
 return <main className="admin-shell"><section className="admin-hero"><div className="container"><span className="eyebrow">إعدادات الموقع</span><h1>تحكم بهوية المنصة ومعلومات الفريق</h1><p className="lead small">عدّل المعلومات العامة من هنا بدلاً من تعديل الكود يدوياً.</p></div></section><section className="section"><div className="container settings-layout"><aside className="card settings-preview"><img src="/logo.png" alt="شعار الفريق"/><span>معاينة سريعة</span><h2>{data.short_name||'اسم الفريق'}</h2><p>{data.slogan||'الشعار النصي'}</p><div><small><MapPin size={15}/>{data.location||'الموقع'}</small><small><Phone size={15}/>{data.phone||'الهاتف'}</small><small><Instagram size={15}/>@{data.instagram||'instagram'}</small></div></aside><form className="card admin-form luxury-form" onSubmit={save}>{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}<div className="form-title"><h2>المعلومات العامة</h2><Sparkles/></div><div className="form-grid two"><label className="label">اسم الفريق الكامل<Building2 size={16}/><input className="input" required value={data.team_name} onChange={e=>setData({...data,team_name:e.target.value})}/></label><label className="label">الاسم المختصر<input className="input" required value={data.short_name} onChange={e=>setData({...data,short_name:e.target.value})}/></label><label className="label wide">الشعار النصي<input className="input" required value={data.slogan} onChange={e=>setData({...data,slogan:e.target.value})}/></label><label className="label wide">وصف الفريق<textarea className="textarea tall" value={data.description} onChange={e=>setData({...data,description:e.target.value})}/></label><label className="label">الموقع<MapPin size={16}/><input className="input" value={data.location} onChange={e=>setData({...data,location:e.target.value})}/></label><label className="label">رقم الهاتف<Phone size={16}/><input className="input" value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><label className="label">إنستغرام<Instagram size={16}/><input className="input" value={data.instagram} onChange={e=>setData({...data,instagram:e.target.value.replace(/^@/,'')})}/></label><label className="label">تاريخ التأسيس<CalendarDays size={16}/><input className="input" value={data.founded_at} onChange={e=>setData({...data,founded_at:e.target.value})}/></label><label className="label wide">موعد/تنبيه مهم<input className="input" value={data.meeting_text} onChange={e=>setData({...data,meeting_text:e.target.value})}/></label><label className="label wide">نص دعوة الانضمام في الرئيسية<textarea className="textarea" value={data.join_intro} onChange={e=>setData({...data,join_intro:e.target.value})}/></label></div><button className="btn" disabled={loading}><Save size={18}/>{loading?'جارٍ الحفظ...':'حفظ الإعدادات'}</button></form></div></section></main>
}
