import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import { isAdminRequest } from '@/lib/admin-auth';
function deny(req:Request){return !isAdminRequest(req)?NextResponse.json({error:'انتهت جلسة الإدارة أو لا تملك صلاحية.'},{status:401}):null}
function slugify(v:string){return v.trim().toLowerCase().replace(/[\u064B-\u0652]/g,'').replace(/[^a-z0-9\u0600-\u06FF]+/g,'-').replace(/^-+|-+$/g,'')}
function payloadFrom(b:any){const title=String(b.title||'').trim();return{slug:String(b.slug||'').trim()||slugify(title),title,excerpt:String(b.excerpt||'').trim(),content:String(b.content||'').trim(),status:String(b.status||'planned'),category:String(b.category||'مجتمعية'),date:b.date||new Date().toISOString().slice(0,10),location:String(b.location||'مصياف').trim(),image_url:String(b.image_url||'/team-banner.jpg').trim(),team:String(b.team||'').trim(),beneficiaries_count:Math.max(0,Number(b.beneficiaries_count||0)),volunteer_hours:Math.max(0,Number(b.volunteer_hours||0)),progress_percent:Math.max(0,Math.min(100,Number(b.progress_percent||0))),is_featured:b.is_featured===true||b.is_featured==='true'}}
export async function GET(req:Request){const d=deny(req);if(d)return d;if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const{data,error}=await supabaseAdmin.from('initiatives').select('*').order('date',{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({initiatives:data||[]})}
export async function POST(req:Request){const d=deny(req);if(d)return d;const b=await req.json();if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const p=payloadFrom(b);if(!p.title||!p.slug)return NextResponse.json({error:'عنوان المبادرة مطلوب.'},{status:400});const{error}=await supabaseAdmin.from('initiatives').insert(p);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,slug:p.slug})}
export async function PUT(req:Request){const d=deny(req);if(d)return d;const b=await req.json();if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const p=payloadFrom(b);if(!p.title||!p.slug)return NextResponse.json({error:'عنوان المبادرة مطلوب.'},{status:400});const{error}=await supabaseAdmin.from('initiatives').upsert(p,{onConflict:'slug'});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,slug:p.slug})}
export async function DELETE(req:Request){const d=deny(req);if(d)return d;if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const slug=new URL(req.url).searchParams.get('slug');if(!slug)return NextResponse.json({error:'معرّف المبادرة مطلوب.'},{status:400});const{error}=await supabaseAdmin.from('initiatives').delete().eq('slug',slug);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
