'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { BarChart3, FileText, UserPlus, Users, Activity, FolderKanban, Settings, RefreshCw, ShieldCheck } from 'lucide-react';
const statusNames:Record<string,string>={active:'نشط',left:'غادر',dismissed:'مفصول',vacation:'إجازة',paused:'معلّق',new:'جديد',reviewing:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض',contacted:'تم التواصل',completed:'مكتملة',in_progress:'قيد التنفيذ',planned:'مخطط'};
export default function AdminDashboardPage(){
 const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
 async function load(){setError('');setLoading(true);const res=await fetch('/api/admin/stats');const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok)return setError(json.error||'تعذر تحميل لوحة البيانات');setData(json)}
 useEffect(()=>{load()},[]);
 const maxTeam=Math.max(1,...Object.values(data?.byTeam||{}).map(Number));
 return <main className="admin-shell"><section className="admin-hero"><div className="container admin-hero-grid"><div><span className="eyebrow">لوحة القيادة</span><h1>كل ما يهم الإدارة في مكان واحد</h1><p className="lead small">مؤشرات فورية، وصول سريع للتعديل، وجلسة إدارة واحدة محمية.</p></div><div className="admin-login-card session-card"><ShieldCheck size={32}/><strong>دخول إداري موثّق</strong><p>لا يتم إرسال كلمة المرور مع عمليات التعديل.</p><button className="btn yellow" onClick={load} disabled={loading}><RefreshCw size={17}/>{loading?'تحديث...':'تحديث المؤشرات'}</button>{error&&<p className="error compact">{error}</p>}</div></div></section><section className="section"><div className="container">
 <div className="admin-shortcuts"><Link href="/admin" className="card shortcut-card"><Users/><strong>إدارة المتطوعين</strong><span>إضافة وتعديل وحالة وصور وبطاقات</span></Link><Link href="/admin/initiatives" className="card shortcut-card"><FolderKanban/><strong>إدارة المبادرات</strong><span>إنشاء وتحديث التقدم والأثر</span></Link><Link href="/admin/applications" className="card shortcut-card"><UserPlus/><strong>طلبات الانضمام</strong><span>مراجعة وقبول وتواصل وملاحظات</span></Link><Link href="/admin/settings" className="card shortcut-card"><Settings/><strong>إعدادات الموقع</strong><span>الهوية والوصف والتواصل والمواعيد</span></Link></div>
 {!data&&!loading&&!error&&<div className="card empty-state">لا توجد بيانات للعرض.</div>}
 {data&&<><div className="dashboard-cards"><div className="card dash-card"><Users/><span>المتطوعون</span><strong>{data.totals.volunteers}</strong><em>النشطون: {data.totals.activeVolunteers}</em></div><div className="card dash-card"><FolderKanban/><span>المبادرات</span><strong>{data.totals.initiatives}</strong><em>قيد التنفيذ: {data.totals.inProgressInitiatives}</em></div><div className="card dash-card"><UserPlus/><span>طلبات الانضمام</span><strong>{data.totals.applications}</strong><em>الجديدة: {data.totals.newApplications}</em></div><div className="card dash-card"><Activity/><span>مؤشرات الأثر</span><strong>{data.metrics.length}</strong><em>مرتبطة بقاعدة البيانات</em></div></div>
 <div className="grid two dashboard-blocks"><div className="card"><h3><BarChart3/> توزيع المتطوعين حسب الفريق</h3><div className="chart">{Object.entries(data.byTeam||{}).map(([k,v])=><div className="bar-row" key={k}><div className="bar-head"><span>{k}</span><b>{String(v)}</b></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.max(8,(Number(v)/maxTeam)*100)}%`}}/></div></div>)}</div></div><div className="card"><h3><FileText/> حالات المبادرات والطلبات</h3><div className="status-grid"><div><h4>المبادرات</h4>{Object.entries(data.initiativesByStatus||{}).map(([k,v])=><p key={k}><span className="pill">{statusNames[k]||k}</span> {String(v)}</p>)}</div><div><h4>طلبات الانضمام</h4>{Object.entries(data.applicationsByStatus||{}).map(([k,v])=><p key={k}><span className="pill yellow">{statusNames[k]||k}</span> {String(v)}</p>)}</div></div></div></div></>}
 </div></section></main>
}
