'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';

type Account = {id:string;full_name:string;email:string;phone?:string;volunteer_slug?:string;status:string;admin_notes?:string;created_at:string;approved_at?:string;last_login_at?:string};
const labels: Record<string,string> = { pending:'بانتظار الموافقة', approved:'مؤكد', rejected:'مرفوض', suspended:'موقوف' };
export default function AdminAccountsPage(){
 const[password,setPassword]=useState('');const[accounts,setAccounts]=useState<Account[]>([]);const[query,setQuery]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[loading,setLoading]=useState(false);
 const filtered=useMemo(()=>accounts.filter(a=>[a.full_name,a.email,a.phone,a.status,a.volunteer_slug].join(' ').includes(query)),[accounts,query]);
 async function load(){setErr('');setMsg('');setLoading(true);const res=await fetch('/api/admin/accounts',{headers:{'x-admin-password':password}});const json=await res.json();setLoading(false);if(!res.ok)return setErr(json.error||'تعذر التحميل');setAccounts(json.accounts||[]);setMsg('تم تحميل الحسابات')}
 async function update(id:string,status:string,admin_notes=''){const res=await fetch('/api/admin/accounts',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,id,status,admin_notes})});const json=await res.json();if(!res.ok)return setErr(json.error||'تعذر التحديث');setMsg('تم تحديث الحساب');await load()}
 async function remove(id:string){if(!confirm('حذف الحساب؟'))return;const res=await fetch(`/api/admin/accounts?id=${encodeURIComponent(id)}&password=${encodeURIComponent(password)}`,{method:'DELETE'});const json=await res.json();if(!res.ok)return setErr(json.error||'تعذر الحذف');setMsg('تم الحذف');await load()}
 return <main className="admin-shell"><section className="admin-hero"><div className="container"><span className="eyebrow">حسابات المتطوعين</span><h1>تأكيد حسابات المتطوعين</h1><p className="lead small">أي حساب جديد يبقى بانتظار موافقة الإدارة قبل الدخول.</p></div></section><section className="section"><div className="container"><div className="card applications-toolbar"><Link className="btn secondary" href="/admin/dashboard">لوحة المؤشرات</Link><input className="input" type="password" placeholder="كلمة مرور الإدارة" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" onClick={load} disabled={loading}>{loading?'تحميل...':'تحميل الحسابات'}</button><input className="input" placeholder="بحث بالاسم أو البريد أو الحالة..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}<div className="applications-grid">{filtered.map(item=><article className="card application-card" key={item.id}><div className="application-head"><h3>{item.full_name}</h3><span className="pill yellow">{labels[item.status]||item.status}</span></div><p className="muted"><strong>البريد:</strong> {item.email}<br/><strong>الهاتف:</strong> {item.phone||'غير محدد'}<br/><strong>ربط المتطوع:</strong> {item.volunteer_slug||'غير مربوط'}<br/><strong>تاريخ الإنشاء:</strong> {new Date(item.created_at).toLocaleDateString('ar')}</p><textarea className="textarea" placeholder="ملاحظات الإدارة" defaultValue={item.admin_notes||''} onBlur={e=>{item.admin_notes=e.target.value}}/><div className="application-actions"><button className="btn" onClick={()=>update(item.id,'approved',item.admin_notes)}>تأكيد الحساب</button><button className="btn yellow" onClick={()=>update(item.id,'suspended',item.admin_notes)}>إيقاف</button><button className="btn danger" onClick={()=>update(item.id,'rejected',item.admin_notes)}>رفض</button><button className="btn secondary" onClick={()=>remove(item.id)}>حذف</button></div></article>)}</div></div></section></main>
}
