'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';

type AppRow={id:string;full_name:string;email:string;phone:string;age?:number;city?:string;specialization?:string;preferred_team?:string;motivation?:string;availability?:string;experience?:string;status:string;admin_notes?:string;created_at:string};
const statusLabels:Record<string,string>={new:'جديد',reviewing:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض',contacted:'تم التواصل'};
export default function AdminApplicationsPage(){
 const[password,setPassword]=useState('');const[items,setItems]=useState<AppRow[]>([]);const[query,setQuery]=useState('');const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[loading,setLoading]=useState(false);
 const filtered=useMemo(()=>items.filter(i=>[i.full_name,i.email,i.phone,i.preferred_team,i.status].join(' ').includes(query)),[items,query]);
 async function load(){setErr('');setMsg('');setLoading(true);const res=await fetch('/api/admin/applications',{headers:{'x-admin-password':password}});const json=await res.json();setLoading(false);if(!res.ok)return setErr(json.error||'تعذر التحميل');setItems(json.applications||[]);setMsg('تم تحميل الطلبات')}
 async function update(id:string,status:string,admin_notes=''){const res=await fetch('/api/admin/applications',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,id,status,admin_notes})});const json=await res.json();if(!res.ok)return setErr(json.error||'تعذر التحديث');setMsg('تم تحديث الطلب');await load()}
 async function remove(id:string){if(!confirm('حذف الطلب؟'))return;const res=await fetch(`/api/admin/applications?id=${encodeURIComponent(id)}&password=${encodeURIComponent(password)}`,{method:'DELETE'});const json=await res.json();if(!res.ok)return setErr(json.error||'تعذر الحذف');setMsg('تم الحذف');await load()}
 return <main className="admin-shell"><section className="admin-hero"><div className="container"><span className="eyebrow">طلبات الانضمام</span><h1>إدارة المتقدمين للتطوع</h1><p className="lead small">مراجعة الطلبات وتغيير حالتها وحفظ ملاحظات الإدارة.</p></div></section><section className="section"><div className="container"><div className="card applications-toolbar"><Link className="btn secondary" href="/admin/dashboard">لوحة المؤشرات</Link><input className="input" type="password" placeholder="كلمة مرور الإدارة" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" onClick={load} disabled={loading}>{loading?'تحميل...':'تحميل الطلبات'}</button><input className="input" placeholder="بحث بالاسم، الفريق، الحالة..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{msg&&<p className="success">{msg}</p>}{err&&<p className="error">{err}</p>}<div className="applications-grid">{filtered.map(item=><article className="card application-card" key={item.id}><div className="application-head"><h3>{item.full_name}</h3><span className="pill yellow">{statusLabels[item.status]||item.status}</span></div><p className="muted"><strong>البريد:</strong> {item.email}<br/><strong>الهاتف:</strong> {item.phone}<br/><strong>الفريق المفضل:</strong> {item.preferred_team||'غير محدد'}<br/><strong>المدينة:</strong> {item.city||'غير محدد'} — <strong>العمر:</strong> {item.age||'غير محدد'}</p><h4>لماذا يريد التطوع؟</h4><p className="muted">{item.motivation}</p>{item.experience&&<><h4>خبرات سابقة</h4><p className="muted">{item.experience}</p></>}<textarea className="textarea" placeholder="ملاحظات الإدارة" defaultValue={item.admin_notes||''} onBlur={e=>{item.admin_notes=e.target.value}}/><div className="application-actions"><button className="btn secondary" onClick={()=>update(item.id,'reviewing',item.admin_notes)}>قيد المراجعة</button><button className="btn" onClick={()=>update(item.id,'accepted',item.admin_notes)}>قبول</button><button className="btn yellow" onClick={()=>update(item.id,'contacted',item.admin_notes)}>تم التواصل</button><button className="btn danger" onClick={()=>update(item.id,'rejected',item.admin_notes)}>رفض</button><button className="btn secondary" onClick={()=>remove(item.id)}>حذف</button></div></article>)}</div></div></section></main>
}
