import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import { isAdminRequest } from '@/lib/admin-auth';

function deny(req: Request) { return !isAdminRequest(req) ? NextResponse.json({ error: 'انتهت جلسة الإدارة أو لا تملك صلاحية.' }, { status: 401 }) : null; }
function split(value: unknown) { return Array.isArray(value) ? value.map(String).map(x=>x.trim()).filter(Boolean) : String(value||'').split(/[،,\n]/).map(x=>x.trim()).filter(Boolean); }
function numberOrNull(value: unknown) { const n=Number(value); return Number.isFinite(n)&&n>0?n:null; }
function payloadFrom(body:any){
  const name=String(body.full_name||'').trim();
  const slug=String(body.slug||'').trim().toLowerCase().replace(/[\u064B-\u0652]/g,'').replace(/[^a-z0-9\u0600-\u06FF]+/g,'-').replace(/^-+|-+$/g,'');
  return { slug, full_name:name, role:String(body.role||'').trim()||null, hierarchy_level:body.hierarchy_level||'volunteer', department:String(body.department||'').trim()||null, team_name:String(body.team_name||'').trim()||null, position_rank:numberOrNull(body.position_rank)??100, specialization:String(body.specialization||'').trim()||null, joined_year:numberOrNull(body.joined_year), joined_date:body.joined_date||null, location:String(body.location||'').trim()||null, age:numberOrNull(body.age), avatar_url:String(body.avatar_url||'').trim()||null, bio:String(body.bio||'').trim()||null, motivation:String(body.motivation||'').trim()||null, skills:split(body.skills), achievements:split(body.achievements), works:split(body.works), certificates:split(body.certificates), social_links:body.social_links||{}, volunteer_status:body.volunteer_status||'active', exit_reason:String(body.exit_reason||'').trim()||null, is_featured:body.is_featured===true||body.is_featured==='true' };
}
export async function GET(req:Request){ const d=deny(req);if(d)return d;if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const{data,error}=await supabaseAdmin.from('volunteers').select('*').order('position_rank',{ascending:true});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({volunteers:data||[]}); }
export async function POST(req:Request){ const d=deny(req);if(d)return d;const body=await req.json();if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const p=payloadFrom(body);if(!p.full_name||!p.slug)return NextResponse.json({error:'الاسم الكامل ومعرّف الصفحة مطلوبان.'},{status:400});const{error}=await supabaseAdmin.from('volunteers').insert(p);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,slug:p.slug}); }
export async function PUT(req:Request){ const d=deny(req);if(d)return d;const body=await req.json();if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const p=payloadFrom(body);if(!p.full_name||!p.slug)return NextResponse.json({error:'الاسم الكامل ومعرّف الصفحة مطلوبان.'},{status:400});const{error}=await supabaseAdmin.from('volunteers').upsert(p,{onConflict:'slug'});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,slug:p.slug}); }
export async function DELETE(req:Request){ const d=deny(req);if(d)return d;if(!supabaseAdmin)return NextResponse.json({error:'إعدادات Supabase الخاصة بالإدارة غير مكتملة.'},{status:500});const slug=new URL(req.url).searchParams.get('slug');if(!slug)return NextResponse.json({error:'معرّف المتطوع مطلوب.'},{status:400});const{error}=await supabaseAdmin.from('volunteers').delete().eq('slug',slug);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true}); }
